import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import gmailRouter from "./gmail";
import dashboardRouter from "./dashboard";
import campaignsRouter from "./campaigns";
import leadsRouter from "./leads";
import templatesRouter from "./templates";
import aiRouter from "./ai";
import draftsRouter from "./drafts";
import uploadsRouter from "./uploads";
import adminRouter from "./admin";
import diagnosticsRouter from "./diagnostics";
import brandingRouter from "./branding";
import trackingRouter from "./tracking";
import mailboxRouter from "./mailbox";
import billingRouter from "./billing";
import sentEmailsRouter from "./sent-emails";
import notificationsRouter from "./notifications";
import composeRouter from "./compose";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(gmailRouter);
router.use(dashboardRouter);
router.use(campaignsRouter);
router.use(leadsRouter);
router.use(templatesRouter);
router.use(aiRouter);
router.use(draftsRouter);
router.use(uploadsRouter);
router.use(adminRouter);
router.use(diagnosticsRouter);
router.use(brandingRouter);
router.use(trackingRouter);
router.use(mailboxRouter);
router.use(billingRouter);
router.use(sentEmailsRouter);
router.use(notificationsRouter);
router.use(composeRouter);

export default router;
